### ISSUE TITLE
下载的图片里面的下划线效果不好

### ISSUE THREAD

**Issue by Lipingchang** [sherlonWang/logodiy#1]
网页里面预览的时候，像g这种字符的下划线，会避开g的下半部分，
但是下载的图片里面，下划线会和g的下半部分相交

>浏览器是Chrome v74

**Comment by sherlonWang** [comment]
看到了，预览的时候像g,j等这样的字符样式是有点问题。多谢提醒！

**Comment by sherlonWang** [comment]
@Lipingchang 下划线问题改好了，我先把issue关了哈
